# Generated by Django 3.2.9 on 2021-12-06 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('category', models.CharField(default='book', max_length=25)),
                ('subCategory', models.CharField(default='subBook', max_length=25)),
                ('slug', models.SlugField(max_length=70, unique_for_date='publish')),
                ('author', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('link', models.URLField(default='example.com', max_length=120)),
                ('secondLink', models.TextField(default='this', max_length=120)),
                ('thirdLink', models.URLField(default='secondExample.com', max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
